env:
  - DISPLAY=:99.0
jdk:
  - oraclejdk8

script:
  - cd src/main/frontend && CLI_WIDTH=80 npm install
  - cd src/main/frontend && npm rum build-semantic-ui
  - ./gradlew build

# Update coverage info on coveralls.io
#after_success:
#  - ./gradlew jacocoTestReport coveralls
