spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  profiles:
    active: dev-postgres
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: format
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
logging:
  level:
    root: INFO
server:
  compression:
    enabled: true
    mime-types: text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048

---

spring:
  profiles: dev,test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    # platform needed to load data-h2.sql
    platform: h2
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
rak:
  login:
    user: kinaseadmin
    password: password
logging:
  level:
    org.sgc: DEBUG

---

# Development is done with a local copy of the Postgres database.
spring:
  profiles: dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
rak:
  login:
    user: kinaseadmin
    password: password
logging:
  level:
    org.sgc: DEBUG

---

# RDS_* environment variables defined in AWS console, ${PORT} set magically (typically 5000)
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
server:
  port: ${PORT}
