spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
logging:
  level:
    root: INFO

---

spring:
  profiles: dev,test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    # platform needed to load data-h2.sql
    platform: h2
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

---

spring:
  profiles: dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

---

# RDS_* environment variables defined in AWS console, ${PORT} set magically (typically 5000)
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
server:
  port: ${PORT}
